# Generated by Django 5.2 on 2025-04-24 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_category_is_active_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.TextField(unique=True, verbose_name='SLUG'),
        ),
    ]
